main_hms/chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("<str:room_name>/", views.ChatView.as_view(), name="chat_room"),
]

main_hms/main_hms/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from main_hms import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reg_auth.urls", namespace="reg_auth")),
    path("users/", include("users.urls", namespace="users")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("chat/", include("chat.urls", namespace="chat")),
    path("payment/", include("payment.urls", namespace="payment")),
    # path("api/", include("api.urls", namespace="api")),
    path("", index, name="home"),
    path("about/", about, name="about"),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_hms/reg_auth/urls.py
from django.urls import path, reverse_lazy
from .views import (
    UserRegistrationView,
    registration_success,
    auth_success,
    CustomPasswordResetConfirmView,
    LoginView,
    UserLogoutView,
)
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetCompleteView,
)

app_name = "reg_auth"

urlpatterns = [
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="reg_auth/password_reset_form.html",
            email_template_name="reg_auth/password_reset_email.html",
            success_url=reverse_lazy("reg_auth:password-reset-done"),
        ),
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="reg_auth/password_reset_done.html"
        ),
        name="password-reset-done",
    ),
    path("register/", UserRegistrationView.as_view(), name="user_registration"),
    path(
        "password-reset/<uidb64>/<token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="reg_auth/password_reset_complete.html"
        ),
        name="password-reset-complete",
    ),
    path("registration_success/", registration_success, name="reg_success"),
    path("authorization_success/", auth_success, name="auth_success"),
    path("login/", LoginView.as_view(), name="user_login"),
    path("logout/", UserLogoutView.as_view(), name="user_logout"),
]

main_hms/reg_auth/models.py
from django.db import models

# Create your models here.

main_hms/reg_auth/forms.py
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CustomSetPasswordForm(SetPasswordForm):
    class Meta:
        model = User
        fields = ["new_password1", "new_password2"]

main_hms/reg_auth/views.py
from django.shortcuts import render, redirect
from rest_framework import generics
from rest_framework.response import Response
from rest_framework import status
from django.contrib.auth import get_user_model
from django.views import View
from .serializers import RegistrationSerializer
import logging
from django.contrib.auth import login, authenticate
from django.contrib.auth import logout
from django.contrib.auth.views import PasswordResetConfirmView
from django.urls import reverse_lazy
from .forms import SetPasswordForm


User = get_user_model()

logger = logging.getLogger(__name__)


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "reg_auth/password_reset_confirm.html"
    success_url = reverse_lazy("reg_auth:password-reset-complete")
    form_class = SetPasswordForm


class UserRegistrationView(generics.GenericAPIView):
    serializer_class = RegistrationSerializer

    def get(self, request, *args, **kwargs):
        logger.info("Пользователь зашел на страницу регистрации")
        return render(request, "reg_auth/register.html", {"title": "Регистрация"})

    def post(self, request, *args, **kwargs):
        logger.info("Пользователь отправил данные на регистрацию")
        logger.info("Полученные данные: %s", request.data)
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            logger.info("Валидация прошла успешно")
            user = serializer.save()
            logger.info(
                "Пользователь успешно сохранён: %s", user
            )
            return redirect("reg_auth:reg_success")
        else:
            logger.warning("Ошибки валидации: %s", serializer.errors)
            return render(request, "reg_auth/register.html", {"errors": serializer.errors})


def registration_success(request):
    logger.info("Пользователь прошел регистрацию")
    return render(
        request, "reg_auth/success_reg.html", {"title": "Регистрация прошла успешно"}
    )


class LoginView(View):
    def get(self, request):
        logger.info("Пользователь зашел на страницу входа")
        return render(request, "reg_auth/login.html")

    def post(self, request):
        logger.info("Пользователь отправил данные на вход")
        email = request.POST.get("email")
        password = request.POST.get("password")

        logger.info("Попытка входа с email: %s", email)

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            logger.info("Пользователь вошел: %s", user.email)
            return redirect("reg_auth:auth_success")
        else:
            logger.warning("Неверные учетные данные для email: %s", email)
            error = "Неправильный email или пароль."
            return render(request, "reg_auth/login.html", {"error": error})


def auth_success(request):
    logger.info("Пользователь прошел вход")
    return render(
        request, "reg_auth/success_auth.html", {"title": "Авторизация прошла успешно"}
    )


def access_denied(request):
    logger.info("Пользователь не авторизован")
    return render(request, "main_hms/access_denied.html")


class UserLogoutView(View):
    def get(self, request):
        logger.info("Пользователь вышел из аккаунта")
        logout(request)
        return redirect("home")

main_hms/reg_auth/templates/reg_auth/login.html
<!-- login.html -->
{% extends "main_hms/base.html" %}

{% block title %}Вход{% endblock %}

{% block content %}
<h1>Вход пользователя</h1>
<form id="login-form" method="post" action="{% url 'reg_auth:user_login' %}">
    {% csrf_token %}
    {% if error %}
        <div class="alert alert-danger">
            <p>{{ error }}</p>
        </div>
    {% endif %}
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email" required value="{{ request.POST.email }}">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Пароль</label>
        <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary">Войти</button>
    <a href="{% url 'reg_auth:password-reset' %}" class="btn btn-link">Забыли пароль?</a>
</form>
{% endblock %}

main_hms/reg_auth/templates/reg_auth/logout.html
{% extends "main_hms/base.html" %}

{% block title %}Выход{% endblock %}

{% block content %}
<h1>Выход</h1>
<p>Вы действительно хотите выйти?</p>
<form method="post" action="{% url 'reg_auth:suser_logout' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Выйти</button>
</form>
{% endblock %}

main_hms/reg_auth/templates/reg_auth/password_reset_complete.html
{% extends "main_hms/base.html" %}

{% block title %}Пароль изменен!{% endblock %}

{% block content %}
<p>Поздравляем! Ваш пароль был изменен.</p>
<p><a href="{% url 'reg_auth:user_login' %}">Войти в свою учетную запись</a></p>
{% endblock %}

main_hms/reg_auth/templates/reg_auth/password_reset_confirm.html
{% extends "main_hms/base.html" %}

{% block title %}Сброс пароля{% endblock %}

{% block content %}
<h1>Введите новый пароль</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>
{% endblock %}

main_hms/reg_auth/templates/reg_auth/password_reset_done.html
{% extends "main_hms/base.html" %}

{% block title %}Сброс пароля{% endblock %}
{% block content %}
<p>Вы получили Email с инструкциями по сбросу пароля.</p>
<p>Если вы не получили Email, проверьте папку со спамом и корректность введёной почты.</p>
{% endblock %}

main_hms/reg_auth/templates/reg_auth/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'reg_auth:password-reset-confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

main_hms/reg_auth/templates/reg_auth/password_reset_form.html
{% extends "main_hms/base.html" %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}
<h1>Восстановление пароля</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сбросить пароль по Email</button>
</form>
{% endblock %}

main_hms/reg_auth/templates/reg_auth/register.html
{% extends "main_hms/base.html" %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h1>Регистрация пользователя</h1>
<form id="registration-form" onsubmit="registerUser(event)">
    {% csrf_token %}
    <div class="mb-3">
        <label for="username" class="form-label">Ваш логин</label>
        <input type="text" class="form-control" id="username" name="username" required>
    </div>
    <div class="mb-3">
        <label for="name" class="form-label">Имя</label>
        <input type="text" class="form-control" id="name" name="name" required>
    </div>
    <div class="mb-3">
        <label for="surname" class="form-label">Фамилия</label>
        <input type="text" class="form-control" id="surname" name="surname">
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email" required>
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Пароль</label>
        <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
</form>

<div id="error-message" style="color: red;"></div>

<script>
async function registerUser(event) {
    event.preventDefault();

    const username = document.getElementById('username').value;
    const name = document.getElementById('name').value;
    const surname = document.getElementById('surname').value;
    const email = document.getElementById('email').value;
    const password = document.getElementById('password').value;

    document.getElementById('error-message').textContent = '';

    try {
        const response = await fetch('/register/', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ username, name, surname, email, password }),
        });

        if (response.ok) {
            if (response.redirected) {
                window.location.href = response.url;
            } else {
                const data = await response.json();
                localStorage.setItem('access_token', data.access);
                localStorage.setItem('refresh_token', data.refresh);
                window.location.href = '/registration_success/';
            }
        } else {
            const errorData = await response.json();
            let errorMessages = '';
            for (const key in errorData) {
                if (errorData.hasOwnProperty(key)) {
                    errorMessages += `${key}: ${errorData[key].join(', ')}\n`;
                }
            }
            document.getElementById('error-message').textContent = errorMessages;
        }
    } catch (error) {
        console.error("Ошибка при регистрации:", error);
        document.getElementById('error-message').textContent = 'Произошла ошибка при отправке данных. Попробуйте снова.';
    }
}
</script>
{% endblock %}

main_hms/reg_auth/templates/reg_auth/success_auth.html
{% extends "main_hms/base.html" %}

{% block title %}Вход{% endblock %}

{% block content %}
<div class="alert alert-success" role="alert" style="border-radius: 10px;">
    Авторизация прошла успешно!
</div>
<a href="/" class="btn btn-primary">На главную страницу</a>
{% endblock %}

main_hms/reg_auth/templates/reg_auth/success_reg.html
{% extends "main_hms/base.html" %}

{% block title %}Вход{% endblock %}

{% block content %}
<div class="alert alert-success" role="alert" style="border-radius: 10px;">
    Регистрация прошла успешно! Необходимо авторизоваться!
</div>
<a href="{% url 'reg_auth:user_login' %}" class="btn btn-primary">Авторизоваться</a>
{% endblock %}