main_hms/chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("<str:room_name>/", views.ChatView.as_view(), name="chat_room"),
]

main_hms/main_hms/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from main_hms import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reg_auth.urls", namespace="reg_auth")),
    path("users/", include("users.urls", namespace="users")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("chat/", include("chat.urls", namespace="chat")),
    path("payment/", include("payment.urls", namespace="payment")),
    # path("api/", include("api.urls", namespace="api")),
    path("", index, name="home"),
    path("about/", about, name="about"),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_hms/posts/urls.py
from django.urls import path
from posts import views
from django.views.decorators.cache import cache_page


app_name = "posts"

urlpatterns = [
    path("", cache_page(60 * 1)(views.PostsView.as_view()), name="posts"),
    path("create/", views.PostCreate.as_view(), name="create_post"),
    path("update/<slug:slug>/", views.PostUpdate.as_view(), name="update_post"),
    path("delete/<slug:slug>/", views.PostDelete.as_view(), name="delete_post"),
    path("<slug:slug>/", views.PostDetail.as_view(), name="post_detail"),
]

main_hms/reg_auth/urls.py
from django.urls import path, reverse_lazy
from .views import (
    UserRegistrationView,
    registration_success,
    auth_success,
    CustomPasswordResetConfirmView,
    LoginView,
    UserLogoutView,
)
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetCompleteView,
)

app_name = "reg_auth"

urlpatterns = [
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="reg_auth/password_reset_form.html",
            email_template_name="reg_auth/password_reset_email.html",
            success_url=reverse_lazy("reg_auth:password-reset-done"),
        ),
        name="password-reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="reg_auth/password_reset_done.html"
        ),
        name="password-reset-done",
    ),
    path("register/", UserRegistrationView.as_view(), name="user_registration"),
    path(
        "password-reset/<uidb64>/<token>/",
        CustomPasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="reg_auth/password_reset_complete.html"
        ),
        name="password-reset-complete",
    ),
    path("registration_success/", registration_success, name="reg_success"),
    path("authorization_success/", auth_success, name="auth_success"),
    path("login/", LoginView.as_view(), name="user_login"),
    path("logout/", UserLogoutView.as_view(), name="user_logout"),
]

main_hms/users/urls.py
from django.urls import path
from users import views

app_name = "users"

urlpatterns = [
    path("get-user-slug/", views.get_user_slug, name="get_user_slug"),
    path("profile/<slug:slug>/", views.UserDetail.as_view(), name="user_detail"),
]

main_hms/main_hms/views.py
from django.shortcuts import render
from django.contrib.auth import get_user_model
import logging
from django.contrib.auth.views import PasswordResetConfirmView


User = get_user_model()

logger = logging.getLogger(__name__)


def index(request):
    logger.info("Главная страница")
    if request.user.is_authenticated:
        user = request.user
    else:
        user = None
    context = {"user": user, "title": "Main page"}
    return render(request, "main_hms/index.html", context)


def about(request):
    logger.info("О нас")
    if request.user.is_authenticated:
        user = request.user
    else:
        user = None
    context = {"user": user, "title": "How it works"}
    return render(request, "main_hms/about.html", context)

main_hms/main_hms/templates/main_hms/about.html
{% extends "main_hms/base.html" %} 

{% load static %}

{% block title %}О нас{% endblock %}

{% block content %}
<div class="about-page-container">
    <div class="image-container">
        <img src="{% static 'main_hms/images/about_page_head.jpg' %}" alt="about_page_head" class="background-image" />
        <div class="overlay-text">
            <h1>Откройте для себя доступный, аутентичный и безопасный способ путешествовать по миру.</h1>
            <p>Узнайте, как вы можете обменять жилье на свой следующий отпуск.</p>
        </div>
    </div>
    <h2 class="text-center mt-4 before">Создайте свой аккаунт и заполните профиль!</h2>
    <ul>
        <li class="text-center mt-4">Представьтесь и выберите свои любимые направления</li>
        <li class="text-center mt-4">Добавьте фото своего дома</li>
        <li class="text-center mt-4">Добавьте информацию о доступности вашего дома в календарь</li>
    </ul>
    <h2 class="text-center mt-4 before">Ищите дома в интересующих вас пунктах назначения и отправляйте запросы на обмен</h2>
    <ul>
        <li class="text-center mt-4">Отправляйте персонализированные сообщения и отвечайте на запросы других участников</li>
        <li class="text-center mt-4">Организуйте детали вашего обмена через систему обмена сообщениями HomeSwap</li>
    </ul>
    <h2 class="text-center mt-4 before">Станьте участником и завершите свой обмен!</h2>
    <ul>
        <li class="text-center mt-4">После согласования деталей обмен должен быть одобрен принимающей стороной</li>
        <li class="text-center mt-4">Регистрация за 220 долларов на год для неограниченного количества обменов</li>
    </ul>
</div>
{% endblock %}

main_hms/main_hms/templates/main_hms/access_denied.html
{% extends 'main_hms/base.html' %}

{% block title %}Страница недоступна{% endblock %}

{% block content %}
<h1>Страница недоступна</h1>
<a href="/" class="btn btn-primary">На главную страницу</a>
{% endblock %}

main_hms/main_hms/templates/main_hms/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <!-- Обязательные метатеги -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />

    <!-- Подключение иконки сайта -->
    <link rel="shortcut icon" type="image/png" href="{% static 'main_hms/images/homeswap_small.ico' %}" />

    <!-- Подключение пользовательских стилей -->
    <link rel="stylesheet" type="text/css" href="{% static 'main_hms/css/styles.css' %}">

    <!-- Заголовок страницы -->
    <title>{% block title %}HomeSwap{% endblock %}</title>
</head>
<body>
    <!-- Навигационное меню -->
    <nav class="navbar navbar-expand-lg navbar-light bg-orange">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">HomeSwap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto">
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'about' %}">О нас</a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'posts:posts' %}">К списку объявлений</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'posts:create_post' %}">Выложить объявление</a>
                  </li>
                  {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" id="profile-link">Профиль {{ user.username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'reg_auth:user_logout' %}">Выйти</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'reg_auth:user_registration' %}">Зарегистрироваться</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'reg_auth:user_login' %}">Войти</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Контент страницы -->
    <div class="container mt-4">{% block content %}{% endblock %}</div>

    <!-- Футер -->
    <footer class="bg-light text-center text-lg-start mt-4">
        <div class="text-center p-3">© 2024 HomeSwap</div>
    </footer>

    <!-- Подключение JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Ваш JavaScript-код -->
    <script>
      document.addEventListener('DOMContentLoaded', function() {
          fetch("{% url 'users:get_user_slug' %}", {
              headers: {
                  'X-Requested-With': 'XMLHttpRequest'
              },
              credentials: 'include'
          })
          .then(response => {
              if (response.status === 401) {
                  // Пользователь не авторизован
                  return;
              }
              if (!response.ok) {
                  throw new Error('Network response was not ok');
              }
              return response.json();
          })
          .then(data => {
              if (data && data.profile_url) {
                  var profileLink = document.getElementById('profile-link');
                  if (profileLink) {
                      profileLink.href = data.profile_url;
                  }
              }
          })
          .catch(error => {
              console.log('Ошибка:', error);
              // Дополнительная обработка ошибок
          });
      });

  </script>
</body>
</html>

main_hms/main_hms/templates/main_hms/index.html
{% extends "main_hms/base.html" %}

{% load static %}

{% block title %}Главная страница{% endblock %}

{% block content %}
<div class="main-page-container">
    <h1 class="text-center mt-4">Путешествуй по всему миру дешевле, меняясь домами!</h1>
    <div class="image-container">
        <img src="{% static 'main_hms/images/house_main_page.jpg' %}" alt="house_main_page" class="background-image" />
        <!-- Если хотите добавить текст поверх изображения, раскомментируйте ниже -->
        <!-- 
        <div class="overlay-text">
            <h1>Добро пожаловать в HomeSwap!</h1>
            <p>Меняйтесь домами и путешествуйте с комфортом.</p>
        </div>
        -->
    </div>
</div>
{% endblock %}

main_hms/main_hms/templates/main_hms/login.html
<!-- login.html -->
{% extends "main_hms/base.html" %}

{% block title %}Вход{% endblock %}

{% block content %}
<h1>Вход пользователя</h1>
<form id="login-form" method="post" action="{% url 'user_login' %}">
    {% csrf_token %}
    {% if error %}
        <div class="alert alert-danger">
            <p>{{ error }}</p>
        </div>
    {% endif %}
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email" required value="{{ request.POST.email }}">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Пароль</label>
        <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary">Войти</button>
    <a href="{% url 'password-reset' %}" class="btn btn-link">Забыли пароль?</a>
</form>
{% endblock %}

main_hms/main_hms/templates/main_hms/logout.html
{% extends "main_hms/base.html" %}

{% block title %}Выход{% endblock %}

{% block content %}
<h1>Выход</h1>
<p>Вы действительно хотите выйти?</p>
<form method="post" action="{% url 'user_logout' %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Выйти</button>
</form>
{% endblock %}

main_hms/main_hms/templates/main_hms/password_reset_complete.html
{% extends "main_hms/base.html" %}

{% block title %}Пароль изменен!{% endblock %}

{% block content %}
<p>Поздравляем! Ваш пароль был изменен.</p>
<p><a href="{% url 'user_login' %}">Войти в свою учетную запись</a></p>
{% endblock %}

main_hms/main_hms/templates/main_hms/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password-reset-confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

main_hms/main_hms/templates/main_hms/register.html
{% extends "main_hms/base.html" %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h1>Регистрация пользователя</h1>
<form id="registration-form" onsubmit="registerUser(event)">
    {% csrf_token %}
    <div class="mb-3">
        <label for="username" class="form-label">Ваш логин</label>
        <input type="text" class="form-control" id="username" name="username" required>
    </div>
    <div class="mb-3">
        <label for="name" class="form-label">Имя</label>
        <input type="text" class="form-control" id="name" name="name" required>
    </div>
    <div class="mb-3">
        <label for="surname" class="form-label">Фамилия</label>
        <input type="text" class="form-control" id="surname" name="surname">
    </div>
    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="email" class="form-control" id="email" name="email" required>
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Пароль</label>
        <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <!-- <div class="mb-3">
        <label for="avatar_url" class="form-label">Аватар</label>
        <input type="avatar_url" class="form-control" id="avatar_url" name="avatar_url">
    </div> -->
    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
</form>

<script>
async function registerUser(event) {
    event.preventDefault(); // Предотвращаем перезагрузку страницы

    const username = document.getElementById('username').value;
    const name = document.getElementById('name').value;
    const surname = document.getElementById('surname').value;
    const email = document.getElementById('email').value;
    const password = document.getElementById('password').value;

    const response = await fetch('/api/register/', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({ username, name, surname, email, password }),
    });

    if (response.ok) {
        const data = await response.json();
        // Сохраните токены в localStorage или sessionStorage
        localStorage.setItem('access_token', data.access);
        localStorage.setItem('refresh_token', data.refresh);
        // Перенаправьте пользователя на защищённую страницу
        window.location.href = '/registration_success/'; // или другая страница
    } else {
        const errorData = await response.json();
        alert('Ошибка: ' + JSON.stringify(errorData));
    }
}
</script>
{% endblock %}

main_hms/main_hms/templates/main_hms/success.html
{% extends "main_hms/base.html" %}

{% block title %}Вход{% endblock %}

{% block content %}
<div class="alert alert-success" role="alert" style="border-radius: 10px;">
    Регистрация или авторизация прошла успешно!
</div>
<a href="/" class="btn btn-primary">На главную страницу</a>
{% endblock %}

main_hms/main_hms/templates/main_hms/success_reg.html
{% extends "main_hms/base.html" %}

{% block title %}Вход{% endblock %}

{% block content %}
<div class="alert alert-success" role="alert" style="border-radius: 10px;">
    Регистрация прошла успешно! Необходимо авторизоваться!
</div>
<a href="{% url 'user_login' %}" class="btn btn-primary">Авторизоваться</a>
{% endblock %}