main_hms/chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("<str:room_name>/", views.ChatView.as_view(), name="chat_room"),
]

main_hms/main_hms/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from main_hms import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reg_auth.urls", namespace="reg_auth")),
    path("users/", include("users.urls", namespace="users")),
    path("posts/", include("posts.urls", namespace="posts")),
    path("chat/", include("chat.urls", namespace="chat")),
    path("payment/", include("payment.urls", namespace="payment")),
    # path("api/", include("api.urls", namespace="api")),
    path("", index, name="home"),
    path("about/", about, name="about"),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_hms/posts/urls.py
from django.urls import path
from posts import views
from django.views.decorators.cache import cache_page


app_name = "posts"

urlpatterns = [
    path("", cache_page(60 * 1)(views.PostsView.as_view()), name="posts"),
    path("create/", views.PostCreate.as_view(), name="create_post"),
    path("update/<slug:slug>/", views.PostUpdate.as_view(), name="update_post"),
    path("delete/<slug:slug>/", views.PostDelete.as_view(), name="delete_post"),
    path("<slug:slug>/", views.PostDetail.as_view(), name="post_detail"),
]

main_hms/posts/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


# Функция для генерации уникального slug
def generate_unique_slug(post):
    # Преобразуем заголовок поста в slug
    original_slug = slugify(post.title)
    slug = original_slug
    queryset = Posts.objects.filter(slug__startswith=original_slug).order_by("-slug")

    # Если уже существуют посты с похожим slug, добавляем числовой суффикс
    if queryset.exists():
        last_slug = queryset.first().slug
        try:
            # Извлекаем последний суффикс из найденного slug
            slug_num = int(last_slug.split("-")[-1])
            slug = f"{original_slug}-{slug_num + 1}"
        except (ValueError, IndexError):
            # Если нет числового суффикса, просто добавляем "-1"
            slug = f"{original_slug}-1"

    return slug


class Posts(models.Model):
    title = models.CharField("Title", max_length=100, null=False, blank=False)
    slug = models.SlugField("Slug", max_length=100, blank=True, unique=True)
    image = models.ImageField("Image", upload_to="posts/", null=True, blank=True)
    content = models.TextField("Content", max_length=1500, null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    available = models.BooleanField("Available", default=True)

    user = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="posts"
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = generate_unique_slug(self)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"


class PostsManager(models.Manager):

    def get_queryset(self):
        return (
            super(PostsManager, self)
            .get_queryset()
            .select_related("user")
            .filter(available=True)
        )


class PostsProxy(Posts):

    objects = PostsManager()

    class Meta:
        proxy = True

main_hms/posts/forms.py
from django import forms
from .models import Posts


class PostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = ["title", "image", "content", "available"]

    title = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Введите заголовок"}
        ),
    )

    image = forms.ImageField(
        required=False, widget=forms.FileInput(attrs={"class": "form-control"})
    )

    content = forms.CharField(
        max_length=1500,
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "Введите содержание поста"}
        ),
    )

    available = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={"class": "form-check-input"})
    )

main_hms/posts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from django.contrib.auth import get_user_model
from posts.utils import generate_chat_hash
from .models import Posts
from .forms import PostForm
from django.utils.text import slugify
from django.core.exceptions import ObjectDoesNotExist
from .documents import *
import logging


logger = logging.getLogger(__name__)

User = get_user_model()


def generate_unique_slug(post):
    logger.info("Генерация уникального slug поста")
    original_slug = slugify(post.title)
    slug = original_slug
    queryset = Posts.objects.filter(slug__startswith=original_slug).order_by("-slug")
    
    if queryset.exists():
        last_slug = queryset.first().slug
        try:
            slug_num = int(last_slug.split("-")[-1])
            slug = f"{original_slug}-{slug_num + 1}"
        except (ValueError, IndexError):
            slug = f"{original_slug}-1"
    else:
        slug = original_slug
    return slug


class PostDetail(View):
    def get(self, request, slug):
        logger.info("Получение поста")
        post = get_object_or_404(Posts, slug=slug)

        author_slug = post.user.slug
        viewer_slug = request.user.slug
        chat_hash = generate_chat_hash(slug, author_slug, viewer_slug)

        context = {"post": post, "chat_hash": chat_hash}
        return render(request, "posts/post_detail.html", context)


class PostsView(View):
    def get(self, request):
        logger.info("Получение списка или поиск постов")
        query = request.GET.get("q", "").strip()
        context = {}

        try:
            if query:
                logger.info(f'Выполнение поиска по запросу: "{query}"')
                search = PostDocument.search().query(
                    "bool",
                    must=[
                        {
                            "multi_match": {
                                "query": query,
                                "fields": ["title", "content"],
                            }
                        }
                    ],
                    filter=[{"term": {"available": True}}],
                )
                response = search.execute()
                posts = response.hits
                context["query"] = query
            else:
                logger.info("Отображение всех доступных постов")
                posts = Posts.objects.filter(available=True)
                context["query"] = ""

            context["posts"] = posts
        except Exception as e:
            logger.error(f"Ошибка при получении постов: {e}")
            context["posts"] = []
            context["error"] = "Произошла ошибка при загрузке постов."

        return render(request, "posts/posts.html", context)


class PostCreate(View):
    def get(self, request):
        logger.info("Отображение формы создания поста")
        form = PostForm()
        return render(request, "posts/post_create.html", {"form": form})

    def post(self, request):
        logger.info("Создание нового поста")
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)

            try:
                post.user = User.objects.get(id=request.user.id)
            except ObjectDoesNotExist:
                return render(
                    request,
                    "posts/post_create.html",
                    {"form": form, "error": "Пользователь не найден."},
                )

            post.slug = generate_unique_slug(post)

            post.save()
            return redirect("posts:post_detail", slug=post.slug)
        else:
            return render(request, "posts/post_create.html", {"form": form})


class PostUpdate(View):
    def get(self, request, slug):
        logger.info("Отображение формы редактирования поста")
        post = get_object_or_404(Posts, slug=slug)
        form = PostForm(instance=post)
        return render(request, "posts/post_update.html", {"form": form, "post": post})

    def post(self, request, slug):
        logger.info("Обновление поста")
        post = get_object_or_404(Posts, slug=slug)
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect("posts:post_detail", slug=post.slug)
        else:
            return render(
                request, "posts/post_update.html", {"form": form, "post": post}
            )


class PostDelete(View):
    def post(self, request, slug):
        logger.info("Удаление поста")
        post = get_object_or_404(Posts, slug=slug)
        post.delete()
        logger.info("Удаление поста: %s", post.title)
        return redirect("posts:posts")

main_hms/posts/templates/posts/post_create.html
{% extends "main_hms/base.html" %}

{% block title %}Создать новый пост{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="text-center">Создать новый пост</h2>
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <!-- Здесь будут отображаться поля формы -->
        {{ form.as_p }}
        
        <div class="text-center mt-4">
            <button type="submit" class="btn btn-primary">Создать пост</button>
        </div>
    </form>
</div>
{% endblock %}

main_hms/posts/templates/posts/post_detail.html
{% extends 'main_hms/base.html' %}
{% block content %}
<div class="post-container" style="max-width: 800px; margin: 0 auto; padding: 20px;">
    <h1 class="text-center">{{ post.title }}</h1>
    <p class="text-center">{{ post.created_at|date:"d M Y" }}</p>

    <!-- Отображение изображения поста -->
    {% if post.image %}
    <div class="text-center mb-4">
        <img src="{{ post.image.url }}" alt="{{ post.title }}" style="max-width: 100%; height: auto; width: 600px; height: 400px; object-fit: cover; border-radius: 8px;">
    </div>
    {% endif %}

    <p class="post-content" style="text-align: justify; font-size: 1.1rem; line-height: 1.6;">
        {{ post.content }}
    </p>

    <!-- Кнопки должны быть видно только автору -->
    {% if request.user.is_authenticated and request.user == post.user %}
    <div class="button-group" style="display: flex; justify-content: space-around; margin-top: 20px;">
        <a href="{% url 'posts:update_post' post.slug %}" class="btn btn-primary" style="width: 45%; padding: 10px 0; text-align: center;">Изменить пост</a>
        <form action="{% url 'posts:delete_post' post.slug %}" method="post" style="width: 45%;">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" style="width: 100%; padding: 10px 0;">Удалить пост</button>
        </form>
    </div>
    {% else %}
    <div>
        <a href="{% url 'chat:chat_room' chat_hash %}" class="btn btn-primary" style="width: 45%; padding: 10px 0; text-align: center;">Чат с автором</a>
    </div>
    {% endif %}
</div>
{% endblock %}

main_hms/posts/templates/posts/post_update.html
{% extends "main_hms/base.html" %}

{% block title %}Обновить пост{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="text-center">Обновить пост {{ post.title }}</h2>
    
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        <!-- Здесь будут отображаться поля формы -->
        {{ form.as_p }}
        
        <div class="text-center mt-4">
            <button type="submit" class="btn btn-primary">Обновить пост</button>
        </div>
    </form>
    
    <!-- Форма для удаления поста -->
    <form method="POST" action="{% url 'posts:delete_post' post.slug %}" class="mt-2">
        {% csrf_token %}
        <div class="text-center">
            <button type="submit" class="btn btn-danger">Удалить пост</button>
        </div>
    </form>
</div>
{% endblock %}

main_hms/posts/templates/posts/posts.html
{% extends 'main_hms/base.html' %}

{% block title %}Posts{% endblock %}

{% block content %}
  <section class="section">
    <div class="container mb-5">
      <h1 class="title">
        {% if query %}
          Результаты поиска по запросу: "{{ query }}"
        {% else %}
          Список постов
        {% endif %}
      </h1>
      <!-- Форма поиска с использованием Bootstrap -->
      <form method="GET" class="d-flex mb-4">
        <input class="form-control me-2" type="search" placeholder="Find a post" name="q" value="{{ query }}">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>

    <div class="container">
      {% if error %}
        <div class="alert alert-danger" role="alert">
          {{ error }}
        </div>
      {% endif %}
      
      <!-- Проверка наличия постов -->
      {% if posts %}
        <!-- Перебор найденных постов -->
        {% for post in posts %}
          <div class="card mb-3 post-card">
            <div class="card-body d-flex align-items-center">
              <div class="post-content flex-grow-1">
                <h5 class="card-title">{{ post.title }}</h5>
                <p class="card-text">{{ post.content|truncatechars:200 }}</p>
                <p class="mb-1"><strong>Posted by:</strong> {{ post.user.username }}</p>
                <p class="mb-2">{{ post.created_at|date:"d M Y" }}</p>
                <a href="{% if post.slug %}{% url 'posts:post_detail' post.slug %}{% else %}#{% endif %}" class="btn btn-primary">Подробнее</a>
              </div>
              {% if post.image %}
                <div class="post-image-container ms-3">
                  <img src="{{ post.image.url }}" alt="{{ post.title }}" class="post-image">
                </div>
              {% endif %}
            </div>
          </div>
        {% endfor %}
      {% else %}
        <!-- Сообщение, если постов нет -->
        <p>No posts found matching your search query.</p>
      {% endif %}
    </div>
  </section>
{% endblock %}